### ISSUE TITLE
GetJsonData()

### ISSUE THREAD

**Issue by Kuro-dev** [sjadrian/java-currency-converter#1]
GetJsonData is a non-static class, that is only used in a static-like context, so I recommend turning it into a static class, if it does not benefit from having it's own state. 

Furthermore please refactor the constructor so that it only does just that: constructing the object. 
complex operations (expecially anything that throws exceptions) should never be done in a constructor but rather in a dedicated method, such as the getData() method.

the reason being that a class like that can be hard to impossible to test using automated testing if you cannot reliably instantiate new objects.

**Comment by sjadrian** [comment]
fixed
